# Configure language servers
[language-server.godotlsp]
command = "nc"
args = ["127.0.0.1", "6005"]
language-id = "gdscript"

[language-server.gdlint]
command = "gdlint"
args = []
language-id = "gdscript"

[language-server.ltex-ls]
command = "ltex-ls"

[language-server.vue-language-server]
command = "vue-language-server"
args = ["--stdio"]

[language-server.typst-lsp]
command = "typst-lsp"
args = []

[language-server.angular-lsp]
command = "ngserver"
args = ["--stdio", "--tsProbeLocations", "$(npm -g root)/typescript/lib", "--ngProbeLocations", "$(npm -g root)/@angular/language-server/bin"]

[language-server.eslint]
command = "vscode-eslint-language-server"
args = ["--stdio"]

# Configure languages
[[language]]
name = "gdscript"
roots = ["project.godot"]
language-servers = [ "godotlsp", "gdlint" ]

[[language]]
name = "markdown"
language-servers = [ "ltex-ls" ]
file-types = ["md"]
scope = "source.markdown"
roots = []

[[language]]
name = "git-commit"
language-servers = [ "ltex-ls" ]
scope = "git.commitmsg"
file-types = ["COMMIT_EDITMSG"]
comment-token = "#"

[[language]]
name = "vue"
language-servers = [ "vue-language-server" ]
auto-format = true
file-types = ["vue"]
injection-regex = "vue"
roots = ["package.json"]
scope = "source.html.vue"

[[language]]
name = "typst"
scope = "source.typst"
injection-regex = "typ(st)?"
auto-format = true
file-types = ["typst", "typ"]
roots = []
comment-token = '//'
language-servers = ["typst-lsp"]
soft-wrap.enable = true

[[grammar]]
name = "typst"
source = { git = "https://github.com/uben0/tree-sitter-typst", rev = "7a2bb249fc555dbcba7d440709927614b8802969" }
