[[language]]
name = "gdscript"
roots = ["project.godot"]
language-server = { command = "nc", args = ["127.0.0.1", "6005"], language-id = "gdscript" }

[[language]]
name = "markdown"
language-server = { command = "ltex-ls" }
file-types = ["md"]
scope = "source.markdown"
roots = []

[[language]]
name = "git-commit"
language-server = { command = "ltex-ls" }
scope = "git.commitmsg"
file-types = ["COMMIT_EDITMSG"]
comment-token = "#"

[[language]]
name = "vue"
language-server = { command = "vue-language-server", args = ["--stdio"] }
auto-format = true
file-types = ["vue"]
injection-regex = "vue"
roots = ["package.json"]
scope = "source.html.vue"
