# Configure language servers
[language-server.godotlsp]
command = "nc"
args = ["127.0.0.1", "6005"]
language-id = "gdscript"

[language-server.gdlint]
command = "gdlint"
args = []
language-id = "gdscript"

[language-server.ltex-ls]
command = "ltex-ls"

[language-server.vue-language-server]
command = "vue-language-server"
args = ["--stdio"]

[language-server.angular-lsp]
command = "ngserver"
args = ["--stdio", "--tsProbeLocations", "$(npm -g root)/typescript/lib", "--ngProbeLocations", "$(npm -g root)/@angular/language-server/bin"]

[language-server.eslint]
command = "vscode-eslint-language-server"
args = ["--stdio"]

# Configure languages
[[language]]
name = "gdscript"
roots = ["project.godot"]
language-servers = [ "godotlsp", "gdlint" ]

[[language]]
name = "markdown"
language-servers = [ "ltex-ls" ]
file-types = ["md"]
scope = "source.markdown"
roots = []

[[language]]
name = "git-commit"
language-servers = [ "ltex-ls" ]
scope = "git.commitmsg"
file-types = ["COMMIT_EDITMSG"]
comment-token = "#"

[[language]]
name = "javascript"
formatter = { command = "prettier", args = ["--parser", "javascript"] }

[[language]]
name = "typescript"
formatter = { command = "prettier", args = ["--parser", "typescript"] }

[[language]]
name = "svelte"
formatter = { command = "prettier", args = ["--plugin", "prettier-plugin-svelte", "--parser", "svelte"] }

[[language]]
name = "vue"
language-servers = [ "vue-language-server" ]
auto-format = true
file-types = ["vue"]
injection-regex = "vue"
roots = ["package.json"]
scope = "source.html.vue"

[[language]]
name = "typst"
auto-format = true
soft-wrap.enable = true
language-servers = ["typst-lsp", "ltex-ls"]
